"""Define Gmail service limits."""

GMAIL_SCOPE = 'https://www.googleapis.com/auth/gmail.modify'
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 20
MAX_ATTACHMENT_BYTES = 25 * 1024 * 1024
MAX_BODY_CHARS = 20_000
MAX_MIME_DEPTH = 20
MAX_THREAD_MESSAGES = 50
MAX_THREAD_PROVIDER_MESSAGES = 100
MAX_LABEL_IDS = 100
MAX_LABELS = 1_000
MAX_ATTACHMENTS = 100
MAX_MIME_PARTS = 500
MAX_MIME_HEADERS = 100
MAX_MIME_SOURCE_CHARS = 600_000
MAX_HEADER_CHARS = 2_000
MAX_SNIPPET_CHARS = 2_000
MAX_FILENAME_CHARS = 255
REQUEST_RETRIES = 2
MAX_SUBJECT_BYTES = 998
MAX_OUTBOUND_BODY_BYTES = 100_000
MAX_RAW_MESSAGE_BYTES = 1_000_000
USER_ID = 'me'
METADATA_HEADERS = (
    'Subject',
    'From',
    'To',
    'Cc',
    'Date',
    'Message-ID',
    'In-Reply-To',
    'References',
)
